### PR TITLE
Fix potential multiple warnings in CI

### LINKED ISSUE #75: Multiple/wrong warnings printed in CI
When I built my site in our GitLabi CI setup, I got the following output multiple times:

```
WARNING:root:
                [git-revision-date-localized-plugin] Running on a GitLab runner might lead to wrong
                Git revision dates due to a shallow git fetch depth.
                Make sure to set GIT_DEPTH to 1000 in your .gitlab-ci.yml file
                (see https://docs.gitlab.com/ee/user/project/pipelines/settings.html#git-shallow-clone).
                
WARNING:root:
                [git-revision-date-localized-plugin] Running on bitbucket pipelines might lead to wrong
                Git revision dates due to a shallow git fetch depth.
                Try setting "clone: depth" to "full" in your pipeline
                (see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
                and search 'depth').
```

I understand the reason for this and have already made my adjustments. But the note regarding BitBucket is wrong, as I'm not on BitBucket. Maybe the different cases could be separated by switch-case or elseif statements to show only a single one.

Also, the `README` of this project says to use `GIT_DEPTH = 0`. The warning says `GIT_DEPTH = 1000`. This can be confusing to new users. IMHO `GIT_DEPTH = 0` is the safe default.

### PR DESCRIPTION
**Pull request by oliversalzburg**
I would hope the fix is as simple as this :)

Fixes #75

### CODE REVIEW

**Comment by timvink** [comment]
Thanks, much appreciated!

**Comment by timvink** [comment]
I've also added your suggestion to change `GIT_DEPTH` to 0 for gitlab in 873a241ff67c0d57213d7a34812210cfadc67a2d

**Comment by timvink** [comment]
FYI, I'll release it to pypi when I have some other issues completed also

**Comment by oliversalzburg** [comment]
Awesome. Thanks :)

**Pull request merged**
